name: beautiful_soup_dart
description: Dart native package inspired by Beautiful Soup 4 Python library. Provides easy ways of navigating, searching, and modifying the HTML tree.
homepage: https://github.com/mzdm/beautiful_soup
version: 0.4.0

environment:
  sdk: ^3.7.0

dependencies:
  html: ^0.15.5

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
